# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Publish Docker image

# Déclencheur : ce workflow se lance à chaque 'push' sur la branche 'main'
on:
  push:
    branches: ['main']

# Les tâches à exécuter
jobs:
  # Nom de la tâche
  push_to_registry:
    name: Push Docker image to Docker Hub
    # La machine sur laquelle la tâche va tourner (fournie par GitHub)
    runs-on: ubuntu-latest
    
    # Les étapes de la tâche
    steps:
      # 1. Récupère le code de ton dépôt
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Se connecte à Docker Hub en utilisant les secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construit et pousse l'image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Construit à partir du Dockerfile à la racine
          context: .
          # Pousse l'image vers le registre Docker Hub
          push: true
          # Nom et tag de l'image
          tags: kheopsian/seederr:latest