version: '3.8'

services:
  seederr:
    image: kheopsian/seederr:latest
    container_name: seederr
    restart: unless-stopped
    
    # 🚨 Volume Mapping: Critical for proper function!
    volumes:
      # Map your main 'data' share, used by qBit/Sonarr/Radarr
      - /mnt/user/data:/data                             # ⬅️ EDIT THIS HOST PATH
      # Map your fast 'cache' drive. MUST ALSO BE MAPPED IN QBITTORRENT.
      - /mnt/disks/your_ssd/cache:/cache                 # ⬅️ EDIT THIS HOST PATH
      
    environment:
      # --- User and Group IDs for file permissions ---
      - PUID=99
      - PGID=100

      # --- Connection Parameters ---
      - QBIT_HOST=192.168.1.100       # IP address of your qBittorrent instance
      - QBIT_PORT=8080                # qBittorrent WebUI Port
      - QBIT_USER=admin               # ⬅️ CHANGE THIS
      - QBIT_PASS=adminadmin          # ⬅️ CHANGE THIS
      - DB_HOST=192.168.1.100         # IP address of your PostgreSQL instance
      - DB_PORT=5432                  # PostgreSQL port
      - DB_NAME=torrents_stats
      - DB_USER=your_db_user          # ⬅️ CHANGE THIS
      - DB_PASS=your_db_password      # ⬅️ CHANGE THIS
      
      # --- Paths SEEN BY THE SCRIPT (inside the container) ---
      # These must match the container-side paths in the volume mappings above.
      - SSD_PATH_IN_CONTAINER=/cache
      - ARRAY_PATH_IN_CONTAINER=/data/downloads

      # --- Logic Parameters ---
      - CHECK_INTERVAL_SECONDS=3600
      - SSD_TARGET_CAPACITY_PERCENT=90
      - MAX_MOVES_PER_CYCLE=1
      - DRY_RUN=true                  # ⚠️ Set to 'false' to enable actual operations!