# Name of the workflow as it will appear in the "Actions" tab of your GitHub repository
name: Publish Docker image

# Trigger: This workflow runs on every push to the 'main' branch
on:
  push:
    branches: ['main']

# The jobs to run
jobs:
  # Name of the job
  push_to_registry:
    name: Push Docker image to Docker Hub
    # The machine to run the job on (provided by GitHub)
    runs-on: ubuntu-latest
    
    # The steps of the job
    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Logs in to Docker Hub using the secrets you configured
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Builds the Docker image and pushes it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The build context (the set of files available to the build) is the project's root directory.
          context: .
          # The path to the Dockerfile, relative to the context.
          file: ./src/Dockerfile
          # Push the image to the registry after a successful build.
          push: true
          # The name and tag for the image.
          tags: kheopsian/seederr:latest